apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "c007-dev"
  namespace: "c007"
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - configmaps
    verbs:
      - get
      - list
      - watch

  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "c007-dev"
  namespace: "c007"
subjects:
  - kind: Group
    name: "c007-groups-dev"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: "c007-dev"
  apiGroup: rbac.authorization.k8s.io
