apiVersion: v1
kind: LimitRange
metadata:
  name: "c002-limits"
  namespace: "c002"
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
