apiVersion: v1
kind: ResourceQuota
metadata:
  name: "c001-quota"
  namespace: "c001"
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "10"

