apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: c003
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/roko1987-k8s/kcd-argentina-apps.git
    targetRevision: main
    path: C003/ux-cloudnative-cdmx
  destination:
    server: https://kubernetes.default.svc
    namespace: c003
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
